package:
  format-version: "1.0.0"
  name: "shd"
  type: "api"
  status: "production"
  required: false
  version: "v1.2.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.22.5"
