package:
  format-version: "1.0.0"
  name: "shd"
  type: "api"
  status: "production"
  required: true
  version: "v1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0"
    - name: "core"
      type: "package"
      version: "v3.14.1"
