import { DisplayMode, OptionPair } from './KeyValueSetSymbolApi';
type AnySymbol<T> = {
    componentId: string;
    symbolId: string;
    symbolType: string;
    visible?: boolean;
    label?: string;
    description?: string;
    readOnly?: boolean;
    value?: T;
    options?: string[];
    min?: number;
    max?: number;
    optionPairs?: OptionPair[];
    displayMode?: DisplayMode;
    selectedOptionPair?: OptionPair;
};
declare function createDefaultSymbol(): any;
export type { AnySymbol };
export { createDefaultSymbol };
