"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.useSymbols = exports.useSymbol = exports.useStringSymbol = exports.useCommentSymbol = exports.useKeyValueSetSymbol = exports.useComboSymbol = exports.useFloatSymbol = exports.useIntegerSymbol = exports.useBooleanSymbol = void 0;
const useBooleanSymbol_1 = __importDefault(require("./useBooleanSymbol"));
exports.useBooleanSymbol = useBooleanSymbol_1.default;
const useIntegerSymbol_1 = __importDefault(require("./useIntegerSymbol"));
exports.useIntegerSymbol = useIntegerSymbol_1.default;
const useFloatSymbol_1 = __importDefault(require("./useFloatSymbol"));
exports.useFloatSymbol = useFloatSymbol_1.default;
const useComboSymbol_1 = __importDefault(require("./useComboSymbol"));
exports.useComboSymbol = useComboSymbol_1.default;
const useKeyValueSetSymbol_1 = __importDefault(require("./useKeyValueSetSymbol"));
exports.useKeyValueSetSymbol = useKeyValueSetSymbol_1.default;
const useCommentSymbol_1 = __importDefault(require("./useCommentSymbol"));
exports.useCommentSymbol = useCommentSymbol_1.default;
const useStringSymbol_1 = __importDefault(require("./useStringSymbol"));
exports.useStringSymbol = useStringSymbol_1.default;
const useSymbol_1 = __importDefault(require("./useSymbol"));
exports.useSymbol = useSymbol_1.default;
const useSymbols_1 = __importDefault(require("./useSymbols"));
exports.useSymbols = useSymbols_1.default;
